### DISCUSSION TITLE
Why does "^[./]" match "../"?

### DISCUSSION THREAD

**Discussion by PaulRBerg** [trivago/prettier-plugin-sort-imports#144] [Q&A] [answered]
Given the following prettier configuration:

```yaml
importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
importOrderSeparation: true
importOrderSortSpecifiers: true
```

And the following imports:

```typescript
import type { Greeter } from "../src/types/Greeter";
import type { SignerWithAddress } from "@nomiclabs/hardhat-ethers/dist/src/signer-with-address";
import type { Fixture } from "ethereum-waffle";
```

This plugin reorders the imports like this:

```typescript
import type { SignerWithAddress } from "@nomiclabs/hardhat-ethers/dist/src/signer-with-address";
import type { Fixture } from "ethereum-waffle";

import type { Greeter } from "../src/types/Greeter";
```

That works for me just fine, but I want to understand why it works in the first place.

Why does `^[./]` match the `../src/types/Greeter` import? I would have expected to have to add another regular expression, e.g. `^[../]`.
