### ISSUE TITLE
Comments on the same line move down

### ISSUE THREAD

**Issue by fcruzel** [trivago/prettier-plugin-sort-imports#149]
**Your Environment**
 * **Prettier version**: 2.6.0
 * **node version** 16.14.0
 * **package manager**: npm@8.3.1
 * **IDE**: IntelliJ IDEA Build #IU-221.5080.210

**Describe the bug**

Same line comments move a few lines down.

**To Reproduce**

```ts
import "zone.js"; // Included with Angular CLI.
```

**Expected behavior**

```ts
import "zone.js"; // Included with Angular CLI.
```

**Screenshots, code sample, etc**

```ts
import "zone.js";

// Included with Angular CLI.
```

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

<details>

  <summary>
      .prettierrc.yml
  </summary>

```yml
trailingComma: "es5"
semi: true
singleQuote: false
arrowParens: always
bracketSpacing: true
quoteProps: as-needed
htmlWhitespaceSensitivity: ignore

importOrderParserPlugins:
    - "typescript"
    - "classProperties"
    - "decorators-legacy"
importOrder:
    - "^@angular(/.*)?$"
    - "^primeng(/.*)?$"
#    - "^(?!\\.).*$"
#    - "^(?!(@app|\\.)).*$"
    - <THIRD_PARTY_MODULES>
    - "^@app(/.*)?$"
    - "^(\\.).*$"
importOrderSeparation: true
importOrderSortSpecifiers: true
```

</details>

**Error log**

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ ] I'm willing to fix this bug 🥇
